/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fi_iki_nop_novelinsight_predicta_PredictaOptimizerNative */

#ifndef _Included_fi_iki_nop_novelinsight_predicta_PredictaOptimizerNative
#define _Included_fi_iki_nop_novelinsight_predicta_PredictaOptimizerNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fi_iki_nop_novelinsight_predicta_PredictaOptimizerNative
 * Method:    startOptimization
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;DDZ)Z
 */
JNIEXPORT jboolean JNICALL Java_fi_iki_nop_novelinsight_predicta_PredictaOptimizerNative_startOptimization
  (JNIEnv *, jobject, jstring, jstring, jstring, jdouble, jdouble, jboolean);

/*
 * Class:     fi_iki_nop_novelinsight_predicta_PredictaOptimizerNative
 * Method:    getRunning
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_fi_iki_nop_novelinsight_predicta_PredictaOptimizerNative_getRunning
  (JNIEnv *, jobject);

/*
 * Class:     fi_iki_nop_novelinsight_predicta_PredictaOptimizerNative
 * Method:    stopOptimization
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_fi_iki_nop_novelinsight_predicta_PredictaOptimizerNative_stopOptimization
  (JNIEnv *, jobject);

/*
 * Class:     fi_iki_nop_novelinsight_predicta_PredictaOptimizerNative
 * Method:    getError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fi_iki_nop_novelinsight_predicta_PredictaOptimizerNative_getError
  (JNIEnv *, jobject);

/*
 * Class:     fi_iki_nop_novelinsight_predicta_PredictaOptimizerNative
 * Method:    getStatus
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fi_iki_nop_novelinsight_predicta_PredictaOptimizerNative_getStatus
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
